#monitor = ,preferred,auto,1.25 #Uncomment this for quick fix
monitor = eDP-1, 1920x1080, 0x0, 1
monitor = DP-1, 1920x1080, auto, 1
monitor = DP-2, 1920x1080, auto, 1
monitor = HDMI-A-2, 1920x1080, 0x0, 1, mirror, eDP-1
